pipeline:
  test:
    image: nbuonin/ocaml4.06-llvm3.6:latest
    pull: true
    commands:
      - touch opam
      - make test

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: general
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Great job TensorFlockernauts.
      {{else}}
        Build {{build.number}} failed. Umm...
      {{/success}}
