version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest 
    environment:
      - OCAML_VERSION: "4.06.0"
      # Tells opam to not ask any questons
      - OPAMYES: 1
      - OPAMJOBS: 2
      - OPAMROOTISOK: 1
    steps:
      - checkout
      # Install the things we need
      - run: apt-get update && apt-get install -y wget build-essential make m4 patch unzip git
      - run: wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.0-rc/opam-2.0.0-rc-x86_64-linux
      - run: chmod +x ${HOME}/opam
      - run: ${HOME}/opam --version 
      # Compile OCaml
      - run: ${HOME}/opam init --compiler=${OCAML_VERSION}
      # Manually set ${HOME}/opam config env 
      - run: ln ${HOME}/opam /bin
      - run: echo "export OPAM_SWITCH_PREFIX='/root/.opam/4.06.0'" >> $BASH_ENV
      - run: echo "export CAML_LD_LIBRARY_PATH='/root/.opam/4.06.0/lib/stublibs:/root/.opam/4.06.0/lib/ocaml/stublibs:/root/.opam/4.06.0/lib/ocaml'" >> $BASH_ENV
      - run: echo "export OCAML_TOPLEVEL_PATH='/root/.opam/4.06.0/lib/toplevel'" >> $BASH_ENV
      - run: echo "export MANPATH=':/root/.opam/4.06.0/man'" >> $BASH_ENV
      - run: echo "export PATH='/root/.opam/4.06.0/bin:$PATH'" >> $BASH_ENV
      - run: make test
